ebay_connector.settings:
  type: config_object
  label: 'eBay Connector settings'
  mapping:
    client_id:
      type: string
      label: 'OAuth client ID'
    client_secret:
      type: string
      label: 'OAuth client secret'
    environment:
      type: string
      label: 'OAuth environment'
